name: hub_of_talking
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.3
  flame: ^1.21.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_image_compress: ^2.3.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  geolocator: ^13.0.1
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.5.2
  image_cropper: ^8.0.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.2
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.3
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.8.0
  universal_platform: ^1.1.0
  url_launcher: ^6.3.1
  version: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  flutter_gen_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  pedantic_mono: any
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon/
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true